services:
     sonata.admin.competition.problem:
          class: Omer\CompetitionBundle\Admin\ProblemAdmin
          arguments:
              - ~
              - Omer\CompetitionBundle\Entity\Problem
              - ~
          tags:
              - { name: sonata.admin, manager_type: orm, group: 'label.group.competition' , label: 'admin.group_label.problem' }
          calls:
              - [ setTranslationDomain, [OmerCompetitionBundle] ]
     sonata.admin.competition.division:
           class: Omer\CompetitionBundle\Admin\DivisionAdmin
           arguments:
               - ~
               - Omer\CompetitionBundle\Entity\Division
               - ~
           tags:
               - { name: sonata.admin, manager_type: orm, group: 'label.group.competition' , label: 'admin.group_label.division' }
           calls:
               - [ setTranslationDomain, [OmerCompetitionBundle] ]
     sonata.admin.competition.problem_type:
           class: Omer\CompetitionBundle\Admin\ProblemTypeAdmin
           arguments:
               - ~
               - Omer\CompetitionBundle\Entity\ProblemType
               - ~
           tags:
               - { name: sonata.admin, manager_type: orm, group: 'label.group.competition' , label: 'admin.group_label.problem_type' }
           calls:
               - [ setTranslationDomain, [OmerCompetitionBundle] ]