services:
     sonata.admin.competition.problem:
          class: Omer\CompetitionBundle\Admin\ProblemAdmin
          arguments:
              - ~
              - Omer\CompetitionBundle\Entity\Problem
              - ~
          tags:
              - { name: sonata.admin, manager_type: orm, group: 'label.group.competition_info' , label: 'admin.group_label.problem' }
          calls:
              - [ setTranslationDomain, [OmerCompetitionBundle] ]