services:
#    omer_gallery.example:
#        class: Omer\GalleryBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    omer_gallery.admin.video:
        class: Omer\GalleryBundle\Admin\VideoAdmin
        arguments: [~, Omer\GalleryBundle\Entity\Video, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Video }
